[package]
edition = "2021"
name = "biobear"
version = "0.4.0"

[lib]
crate-type = ["cdylib"]
name = "biobear"

[dependencies]
pyo3 = "0.18.3"

[dependencies.arrow]
features = ["pyarrow"]
version = "37.0.0"

[dependencies.noodles]
features = ["fasta", "fastq", "gff", "core", "sam", "bam", "vcf", "bed", "bgzf", "bcf"]
version = "0.38.0"

[dependencies.flate2]
version = "1.0.26"

[dependencies.gb-io]
version = "0.7.1"
