# Create a smoketest that just installs the biobear python package and reads an example file

name: Smoke Test

on:
    workflow_dispatch:


jobs:
    test-package:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.7, 3.8, 3.9, "3.10", 3.11]
        steps:
            # setup python
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install biobear
              run: |
                  python -m pip install --upgrade pip
                  pip install biobear

            # Create an example fasta file and try to read it
            - name: Create example fasta file using python
              shell: python
              run: |
                f = open("test.fasta", "w")
                f.write(">test\n")
                f.write("ATGC\n")
                f.close()

            - name: Read example fasta file
              run: |
                python -c "from biobear import FastaReader; print(FastaReader('test.fasta').read())"
